# Generated by Django 4.1.5 on 2023-03-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=25, verbose_name='Name'),
        ),
    ]
